name: deep-signature-2-windows
channels:
  - pyg
  - nvidia
  - pytorch
#  - pytorch3d
  - fvcore
  - iopath
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.7
  - pyg
  - pytorch-sparse
  - pytorch-cluster
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - jupyterlab
  - pandas
  - plotly
  - numba
  - pyvista
  - shapely
  - notebook
#  - fvcore
#  - iopath
#  - pytorch3d
  - pip
  - pip:
      - lightly
      - wandb
      - typed-argument-parser
      - gitpython
      - opencv-python
      - jupyter-bokeh
      - trame
      - noise
      - openpyxl
      - cgal
      - open3d
      - pymesh
      - trimesh
      - libigl
      - sympy
      - pygfx
      - pyvistaqt
      - imageio
      - glfw
      - pytest
      - open3d
      - pygltflib