name: deep-signature-2-ubuntu
channels:
  - pyg
  - nvidia
  - pytorch
#  - pytorch3d
  - fvcore
  - iopath
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.7
  - pyg
  - pytorch-sparse
  - pytorch-cluster
  - igl
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - jupyterlab
  - pandas
  - plotly
  - numba
  - pyvista
  - shapely
  - notebook
  - mesa-libgl-cos6-x86_64
#  - fvcore
#  - iopath
#  - pytorch3d
  - pip
  - pip:
      - lightly
      - wandb
      - typed-argument-parser
      - gitpython
      - opencv-python
      - jupyter-bokeh
      - trame
      - noise
      - openpyxl
      - cgal
      - open3d